apiVersion: v1
kind: Pod
metadata:
  labels:
    run: neveshomework
    service: webserver
  name: neveshomework
spec:
  volumes:
  - name: primeiro-emptydir
    emptyDir:
      sizeLimit: 256Mi

  containers:
  - image: nginx
    name: neveshomework01
    resources:
      limits:
        cpu: "0.5"
        memory: "128Mi"
      requests:
        cpu: "0.2"
        memory: "64Mi"
    volumeMounts:
    - mountPath: /neveshomework
      name: primeiro-emptydir

  - image: busybox
    name: neveshomework02
    args:
    - sleep
    - "1800"

  dnsPolicy: ClusterFirst
  restartPolicy: Always
